const FIFA_TO_PT_BR: Record<string, string> = {
  ALB: "Albânia",
  ALG: "Argélia",
  ANG: "Angola",
  ARG: "Argentina",
  AUS: "Austrália",
  AUT: "Áustria",
  BEL: "Bélgica",
  BIH: "Bósnia e Herzegovina",
  BRA: "Brasil",
  BUL: "Bulgária",
  CAN: "Canadá",
  CHI: "Chile",
  CIV: "Costa do Marfim",
  CMR: "Camarões",
  COL: "Colômbia",
  CRC: "Costa Rica",
  CPV: "Cabo Verde",
  CRO: "Croácia",
  CUW: "Curaçao",
  CZE: "Tchéquia",
  COD: "RD Congo",
  DEN: "Dinamarca",
  ECU: "Equador",
  EGY: "Egito",
  ENG: "Inglaterra",
  ESP: "Espanha",
  FRA: "França",
  GER: "Alemanha",
  GHA: "Gana",
  GRE: "Grécia",
  HUN: "Hungria",
  IRL: "Irlanda",
  IRN: "Irã",
  IRQ: "Iraque",
  ISL: "Islândia",
  ISR: "Israel",
  ITA: "Itália",
  JPN: "Japão",
  JOR: "Jordânia",
  KOR: "Coreia do Sul",
  MAR: "Marrocos",
  MEX: "México",
  NED: "Holanda",
  NGA: "Nigéria",
  NIR: "Irlanda do Norte",
  NOR: "Noruega",
  NZL: "Nova Zelândia",
  PAN: "Panamá",
  PAR: "Paraguai",
  PER: "Peru",
  POL: "Polônia",
  POR: "Portugal",
  QAT: "Catar",
  RSA: "África do Sul",
  ROU: "Romênia",
  KSA: "Arábia Saudita",
  SCO: "Escócia",
  SEN: "Senegal",
  SRB: "Sérvia",
  SUI: "Suíça",
  SVK: "Eslováquia",
  SVN: "Eslovênia",
  SWE: "Suécia",
  TUN: "Tunísia",
  TUR: "Turquia",
  UKR: "Ucrânia",
  URU: "Uruguai",
  USA: "Estados Unidos",
  UZB: "Uzbequistão",
  VEN: "Venezuela",
  WAL: "País de Gales",
};

const ENGLISH_TO_PT_BR: Record<string, string> = {
  "Bosnia and Herzegovina": "Bósnia e Herzegovina",
  "Cape Verde": "Cabo Verde",
  "Cape Verde Islands": "Cabo Verde",
  "Congo DR": "RD Congo",
  "Costa Rica": "Costa Rica",
  "Czech Republic": "Tchéquia",
  "Côte d'Ivoire": "Costa do Marfim",
  England: "Inglaterra",
  Germany: "Alemanha",
  Ghana: "Gana",
  Iraq: "Iraque",
  "IR Iran": "Irã",
  Japan: "Japão",
  Jordan: "Jordânia",
  Morocco: "Marrocos",
  Netherlands: "Holanda",
  "New Zealand": "Nova Zelândia",
  Nigeria: "Nigéria",
  Qatar: "Catar",
  "Saudi Arabia": "Arábia Saudita",
  Scotland: "Escócia",
  Serbia: "Sérvia",
  "South Africa": "África do Sul",
  Switzerland: "Suíça",
  Türkiye: "Turquia",
  Ukraine: "Ucrânia",
  "United States": "Estados Unidos",
  "United States of America": "Estados Unidos",
  Uzbekistan: "Uzbequistão",
  Wales: "País de Gales",
};

export function teamNamePtBr(team: {
  id?: string | null;
  tla?: string | null;
  name: string;
}): string {
  const code = (team.tla ?? team.id ?? "").toUpperCase();
  return FIFA_TO_PT_BR[code] ?? ENGLISH_TO_PT_BR[team.name] ?? team.name;
}
